version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postegres
      - POSTGRES_PASSWORD=lucas123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'
volumes:
  postgres: